### ISSUE TITLE
host port label to lower

### ISSUE THREAD

**Issue by aklockmann** [netappeseries/santricity#10]
Hi,

I just tested the na_santricity_host module and noticed that port_labels defined in uppercase were saved in lowercase on the storage system. In the module examples port labels are written in uppercase too. I expected they were saved in same case as defined in the playbook. 

I found this lines of code where '.lower()' was used for the labels. I guess you're using this to match existing ports with new definitions. I checked saving port labels in uppercase is supported with webservices.

https://github.com/netappeseries/santricity/blob/b95ffc8a8035dc96daebd21da97377a210971076/plugins/modules/na_santricity_host.py#L208 
https://github.com/netappeseries/santricity/blob/b95ffc8a8035dc96daebd21da97377a210971076/plugins/modules/na_santricity_host.py#L356

**Comment by netappeseries** [comment]
@aklockmann The patch release 1.2.12 will resolve your host and host port naming case issue.

If you don't mind and have the time, would you tell me how extensively you've used the roles/modules? Have they been easy to use? Feedback has been sparse and I'm always looking for ways to improve. Either way, I really appreciate you submitting the defect. So thanks!

**Comment by aklockmann** [comment]
Nice! You already fixed this issue. I tested it right now and it works perfect. Great job!

I'm very sorry to tell you, that i just found the ansible-galaxy collection today. My last playbooks with e-series are over one year old. Hence i only knew the legacy "netapp_e_*" modules. Next thing: i do not completely understand the concepts of roles, and used them yet. But i will ;) I really want to and let you know about the santricity ones.

**Comment by netappeseries** [comment]
Glad to help! Roles are really just generic/premade playbooks that are controlled by predefined variables and structures; so all you need to do is lookup in the readme file for the variables you want to set and then execute the role in your playbook. You can do much as you want anything that isn't defined is skipped. You can also use the tags system to control what you want to change/check.

Anyway, if you find yourself with questions or need help you can reach me at ng-eseries-ansible@netapp.com or netapppub.slack.com within the #configurationmgmt channel.
