### ISSUE TITLE
na_santricity_mgmt_interface broken

### ISSUE THREAD

**Issue by chjones45** [netappeseries/santricity#18]
The na_santricity_mgmt_interface module appears to be broken in the latest 1.3.1 release. A simple task like this (ignore the way github wants to format it):

'# Configure Array DNS
  - name: DNS
    ignore_errors: no
    na_santricity_mgmt_interface:
      <<: *arraylogin
      controller: "A"
      port: "1"
      dns_config_method: "static"
      dns_address: "act.ntp.domain.au"
      dns_address_backup: "vic.ntp.domain.au"
    tags: dns

Returns an error that it wants the config_method for the physical interface to be supplied, because the "state: enabled", which must be being passed by the module because my task is not passing it.

Supplying the config_method then in turn wants the IP Address, Mask and Gateway. This means that ALL IP information must be provided to just change DNS or NTP, which is unlike the examples.

Below is the run output:

`root@user-ansible:/home/user/domain-Grid-sgrid02# ansible-playbook -i inventory.yml playbook.yml --extra-vars "target_array=<redacted>" --tags dns -vvv
ansible-playbook [core 2.13.4]
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/dist-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.8.10 (default, Jun 22 2022, 20:18:18) [GCC 9.4.0]
  jinja version = 3.1.2
  libyaml = True
No config file found; using defaults
host_list declined parsing /home/user/domain-Grid-sgrid02/inventory.yml as it did not pass its verify_file() method
script declined parsing /home/user/domain-Grid-sgrid02/inventory.yml as it did not pass its verify_file() method
Parsed /home/user/domain-Grid-sgrid02/inventory.yml inventory source with yaml plugin
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.

PLAYBOOK: playbook.yml ******************************************************************************************************************************************************************************************************************
1 plays in playbook.yml

PLAY [<redacted>] ***************************************************************************************************************************************************************************************************************
META: ran handlers

TASK [DNS] ******************************************************************************************************************************************************************************************************************************
task path: /home/user/domain-Grid-sgrid02/playbook.yml:57
<<redacted>> ESTABLISH LOCAL CONNECTION FOR USER: root
<<redacted>> EXEC /bin/sh -c 'echo ~root && sleep 0'
<<redacted>> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir "` echo /root/.ansible/tmp/ansible-tmp-1663548560.4495761-92791-79842150882343 `" && echo ansible-tmp-1663548560.4495761-92791-79842150882343="` echo /root/.ansible/tmp/ansible-tmp-1663548560.4495761-92791-79842150882343 `" ) && sleep 0'
<<redacted>> Attempting python interpreter discovery
<<redacted>> EXEC /bin/sh -c 'echo PLATFORM; uname; echo FOUND; command -v '"'"'python3.10'"'"'; command -v '"'"'python3.9'"'"'; command -v '"'"'python3.8'"'"'; command -v '"'"'python3.7'"'"'; command -v '"'"'python3.6'"'"'; command -v '"'"'python3.5'"'"'; command -v '"'"'/usr/bin/python3'"'"'; command -v '"'"'/usr/libexec/platform-python'"'"'; command -v '"'"'python2.7'"'"'; command -v '"'"'/usr/bin/python'"'"'; command -v '"'"'python'"'"'; echo ENDFOUND && sleep 0'
<<redacted>> EXEC /bin/sh -c '/usr/bin/python3.8 && sleep 0'
Using module file /root/.ansible/collections/ansible_collections/netapp_eseries/santricity/plugins/modules/na_santricity_mgmt_interface.py
<<redacted>> PUT /root/.ansible/tmp/ansible-local-92786bm72fp8v/tmpghxreqro TO /root/.ansible/tmp/ansible-tmp-1663548560.4495761-92791-79842150882343/AnsiballZ_na_santricity_mgmt_interface.py
<<redacted>> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1663548560.4495761-92791-79842150882343/ /root/.ansible/tmp/ansible-tmp-1663548560.4495761-92791-79842150882343/AnsiballZ_na_santricity_mgmt_interface.py && sleep 0'
<<redacted>> EXEC /bin/sh -c '/usr/bin/python3 /root/.ansible/tmp/ansible-tmp-1663548560.4495761-92791-79842150882343/AnsiballZ_na_santricity_mgmt_interface.py && sleep 0'
<<redacted>> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1663548560.4495761-92791-79842150882343/ > /dev/null 2>&1 && sleep 0'
fatal: [<redacted>]: FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "changed": false,
    "invocation": {
        "module_args": {
            "address": null,
            "api_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "api_url": "https://<IP>:8443/devmgr/v2",
            "api_username": "admin",
            "config_method": null,
            "controller": "A",
            "dns_address": "act.ntp.domain.au",
            "dns_address_backup": "vic.ntp.domain.au",
            "dns_config_method": "static",
            "gateway": null,
            "ntp_address": null,
            "ntp_address_backup": null,
            "ntp_config_method": null,
            "port": 1,
            "ssh": null,
            "ssid": "1",
            "state": "enabled",
            "subnet_mask": null,
            "validate_certs": false
        }
    },
    "msg": "state is enabled but all of the following are missing: config_method"
}

PLAY RECAP ******************************************************************************************************************************************************************************************************************************
<redacted>         : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
`

**Comment by netappeseries** [comment]
I'm adding this to our internal backlog and should be fixed in the up coming release.

**Comment by netappeseries** [comment]
Note that this is the same root issue for https://github.com/netappeseries/santricity/issues/14

**Comment by swartzn** [comment]
This is fixed in release 1.4.0
