### ISSUE TITLE
Unable to set iSCSI Port Speed

### ISSUE THREAD

**Issue by chjones45** [netappeseries/santricity#19]
I just deployed 4 x E5760 Arrays, so there are 8 controllers, each with a 4-Port 25GbE iSCSI HIC, so 32 x 25GbE Ports in total. I used the na_santricity_iscsi_interface module to configure IP settings on all HIC Ports, which worked great. However, the module doesn't allow setting the speed of the ports.

We discovered this when all HIC ports were offline until we manually configured the ports to be 25GbE via SANtricity. It seems the arrays default them to 10GbE and won't connect without manually setting the speed.

Would be awesome if we could configure this via our playbooks.

**Comment by netappeseries** [comment]
Thanks for letting us know. I'll add it to our backlog.

**Comment by swartzn** [comment]
This is fixed in release 1.4.0.
