### ISSUE TITLE
ASUP Proxy authentication

### ISSUE THREAD

**Issue by mamoep** [netappeseries/santricity#4]
The machines support setting username and password for autosupport http(s) proxy delivery via GUI and SMcli. Is this possible with the na_santricity_asup currently? If not, could you please add it.

**Comment by netappeseries** [comment]
I'll look into it.

**Comment by netappeseries** [comment]
It's a fairly simple addition that should have already been there so I'm going to treat it like a bug and try to have an update later today. Thanks for speaking up :)

**Comment by mamoep** [comment]
Thank you for the fast response. The fix is working fine.
